# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.qbgoo.com:
  peer0.orga.qbgoo.com:
  peer1.orga.qbgoo.com:
  peer0.orgb.qbgoo.com:
  peer1.orgb.qbgoo.com:

networks:
  qbgoo_network:

services:

  orderer.qbgoo.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.qbgoo.com
    container_name: orderer.qbgoo.com
    networks:
      - qbgoo_network 

  peer0.orga.qbgoo.com:
    container_name: peer0.orga.qbgoo.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.orga.qbgoo.com
    networks:
      - qbgoo_network 

  peer1.orga.qbgoo.com:
    container_name: peer1.orga.qbgoo.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.orga.qbgoo.com
    networks:
      - qbgoo_network

  peer0.orgb.qbgoo.com:
    container_name: peer0.orgb.qbgoo.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.orgb.qbgoo.com
    networks:
      - qbgoo_network 

  peer1.orgb.qbgoo.com:
    container_name: peer1.orgb.qbgoo.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.orgb.qbgoo.com
    networks:
      - qbgoo_network

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.orga.qbgoo.com:7051
      - CORE_PEER_LOCALMSPID=OrgAMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orga.qbgoo.com/peers/peer0.orga.qbgoo.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orga.qbgoo.com/peers/peer0.orga.qbgoo.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orga.qbgoo.com/peers/peer0.orga.qbgoo.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orga.qbgoo.com/users/Admin@orga.qbgoo.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        #操作peer ,chaincode的代码
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.qbgoo.com
      - peer0.orga.qbgoo.com
      - peer1.orga.qbgoo.com
      - peer0.orgb.qbgoo.com
      - peer1.orgb.qbgoo.com
    networks:
      - qbgoo_network
