# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.qbgoo.com:
    container_name: orderer.qbgoo.com
    image: hyperledger/fabric-orderer:latest
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/qbgoo.com/orderers/orderer.qbgoo.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/qbgoo.com/orderers/orderer.qbgoo.com/tls/:/var/hyperledger/orderer/tls
    - orderer.qbgoo.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.orga.qbgoo.com:
    container_name: peer0.orga.qbgoo.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.orga.qbgoo.com
      - CORE_PEER_ADDRESS=peer0.orga.qbgoo.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.orga.qbgoo.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.orga.qbgoo.com:7051
      - CORE_PEER_LOCALMSPID=OrgAMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/orga.qbgoo.com/peers/peer0.orga.qbgoo.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/orga.qbgoo.com/peers/peer0.orga.qbgoo.com/tls:/etc/hyperledger/fabric/tls
        - peer0.orga.qbgoo.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer1.orga.qbgoo.com:
    container_name: peer1.orga.qbgoo.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.orga.qbgoo.com
      - CORE_PEER_ADDRESS=peer1.orga.qbgoo.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.orga.qbgoo.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.orga.qbgoo.com:7051
      - CORE_PEER_LOCALMSPID=OrgAMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/orga.qbgoo.com/peers/peer1.orga.qbgoo.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/orga.qbgoo.com/peers/peer1.orga.qbgoo.com/tls:/etc/hyperledger/fabric/tls
        - peer1.orga.qbgoo.com:/var/hyperledger/production

    ports:
      - 8051:7051
      - 8053:7053

  peer0.orgb.qbgoo.com:
    container_name: peer0.orgb.qbgoo.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.orgb.qbgoo.com
      - CORE_PEER_ADDRESS=peer0.orgb.qbgoo.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.orgb.qbgoo.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.orgb.qbgoo.com:7051
      - CORE_PEER_LOCALMSPID=OrgBMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/orgb.qbgoo.com/peers/peer0.orgb.qbgoo.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/orgb.qbgoo.com/peers/peer0.orgb.qbgoo.com/tls:/etc/hyperledger/fabric/tls
        - peer0.orgb.qbgoo.com:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053

  peer1.orgb.qbgoo.com:
    container_name: peer1.orgb.qbgoo.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.orgb.qbgoo.com
      - CORE_PEER_ADDRESS=peer1.orgb.qbgoo.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.orgb.qbgoo.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.orgb.qbgoo.com:7051
      - CORE_PEER_LOCALMSPID=OrgBMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/orgb.qbgoo.com/peers/peer1.orgb.qbgoo.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/orgb.qbgoo.com/peers/peer1.orgb.qbgoo.com/tls:/etc/hyperledger/fabric/tls
        - peer1.orgb.qbgoo.com:/var/hyperledger/production
    ports:
      - 10051:7051
      - 10053:7053
